language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
services:
    - redis-server
install:
    - 'pip install -r requirements.txt' 
script:
  - echo $TRAVIS_PYTHON_VERSION
  - cd .. && supybot-test AttackProtector

  - echo "travis_fold:start:#{messages}" && cat "test-logs/messages.log" && echo "travis_fold:end:#{messages}"
